# -*- coding: utf-8 -*-
"""img_download.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EhPHtJs_As959EkbV829oDp5xvrh9A43
"""

import requests as req
from bs4 import BeautifulSoup
import os

url='http://www.google.com/'
content=req.get(url).text
print(content)

soup=BeautifulSoup(content,'lxml')
images=soup.find_all('img')
print(images)
try:
  os.mkdir(os.path.join(os.getcwd(),folder))
  os.chdir(os.path.join(os.getcwd(),folder))
except:
  pass



index=0
for image in images:
  index=index+1
  link=url+image['src']
  name=str(index)+'.jpg'
  print(link)
  
  with open(name,'wb') as f:
    img=req.get(link)
    f.write(img.content)