# -*- coding: utf-8 -*-
"""shortener.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u72R9G9fd4uSYHqI4qWUA-a8sE3bQXl_
"""

import pyshorteners as ps

url='https://www.youtube.com/watch?v=QK0DNbs6BTo'
def shorten(url):
  shortener=ps.Shortener()
  result=shortener.tinyurl.short(url)
  print(result)
shorten(url)